palette = "noctalia"

format = """
[░▒▓](magenta)\
$os\
[](bg:green fg:magenta)\
$directory\
[](fg:green bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:yellow)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:yellow bg:black)\
$time\
[ ](fg:black)\
\n$character"""

[directory]
style = "fg:black bg:green"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Desktop" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:black"
format = '[[ $symbol $branch ](fg:black bg:yellow)]($style)'

[git_status]
style = "bg:black"
format = '[[($all_status$ahead_behind )](fg:black bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:green bg:blue)]($style)'

[bun]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:green bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:green bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:green bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ($version) ](fg:green bg:blue)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:black"
format = '[[  $time ](fg:white bg:black)]($style)'

[os]
style = "bg:magenta fg:black"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#bac6ea"
red       = "#ffb4ab"
green     = "#4fd8eb"
yellow    = "#b1cbd0"
cyan      = "#b1cbd0"
magenta   = "#4fd8eb"
white     = "#e2e2e2"
black     = "#474747"

# Extended palette (Catppuccin-compatible names)
rosewater = "#b1cbd0"
flamingo  = "#ffb4ab"
pink      = "#4fd8eb"
mauve     = "#4fd8eb"
maroon    = "#ffb4ab"
peach     = "#b1cbd0"
teal      = "#b1cbd0"
sky       = "#b1cbd0"
sapphire  = "#bac6ea"
lavender  = "#4fd8eb"

# Text shades
text      = "#e2e2e2"
subtext1  = "#e2e2e2"
subtext0  = "#919191"

# Surface shades
overlay2  = "#919191"
overlay1  = "#919191"
overlay0  = "#474747"
surface2  = "#474747"
surface1  = "#474747"
surface0  = "#131313"
base      = "#131313"
mantle    = "#131313"
crust     = "#131313"
# <<< NOCTALIA STARSHIP PALETTE <<<
